### ISSUE TITLE
How to run this explorer-api on my local?

### ISSUE THREAD

**Issue by SWS-5007** [polkascan/explorer-api#21]
Hi,
I am going to run this api on my local, win_10.
How should I do this?
Please let me know in detail step by step.
Best.

**Comment by SWS-5007** [comment]
When I run this command, `docker-compose up --build`, as Readme, I am getting error below.

> ...
>    - 495af11a3eac Downloading [==================================================>]  313.8k...                   152.2s
>    - 18b045ddb54d Downloading [==================================================>]  1.166M...                   152.2s
>    - f49c2d6d086c Download complete                                                                              152.2s
>    - 14ed0c386119 Download complete                                                                              152.2s
> **unexpected EOF**
> 

And also, I run this command, `export API_DOCKER_FILE="./docker/api/Dockerfile.query.logging" API_DOCKER_IMAGE="polkascan/explorer-api-query-logging" API_DOCKER_COMMAND="bash -c '/usr/src/start-api-query-logging.sh'" && docker-compose up --build`, I am getting same error above.

What is wrong?
How can I solve this problem?

**Comment by SWS-5007** [comment]
Here is my `docker-composer.yml` file.
```
version: "3"

services:
  db:
    image: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: aXMHcwPm4fMJa
      MYSQL_DATABASE: test_explorer
    ports:
      - "3307:3306"

  redis:
    image: "redis:latest"

  polling:
    build:
      context: .
      dockerfile: ./docker/polling/Dockerfile
    image: polkascan/explorer-polling-beta
    command: python polling.py
    depends_on:
      - redis
      - db
      - api
    environment:
      - DB_USERNAME=test_root
      - DB_NAME=test_explorer
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_PASSWORD=aXMHcwPm4fMJa
      - BROADCAST_URI=redis://redis:6379
      - CHAIN_ID=polkadot
      - SENTRY_PROJECT_NAME=explorer-polling-v2
      - SENTRY_SERVER_NAME=polkadapt
      - SENTRY_DSN=

  api:
    build:
      context: .
      dockerfile: ${API_DOCKER_FILE:-./docker/api/Dockerfile}
    image: ${API_DOCKER_IMAGE:-polkascan/explorer-api-beta}
    command: ${API_DOCKER_COMMAND:-bash -c "/usr/src/start-api.sh"}
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
#    # Note: enable when running with Signoz telemetry
#    networks:
#        - default
#        - clickhouse-setup_default
    environment:
      - DB_USERNAME=test_root
      - DB_NAME=test_explorer
      - DB_HOST=mysql
      - DB_PORT=3306
      - BLOCK_LIMIT_COUNT=500000
      - HTTP_MOUNT=/graphql/
      - WS_MOUNT=/graphql-ws/
      - DB_HARVESTER_NAME=test_db
      - DB_PASSWORD=aXMHcwPm4fMJa
      - DOMAIN=localhost
      - SERVER_ADDR=localhost
      - SERVER_PORT=8000
      - WEBSOCKET_URI=ws://localhost:8000
      - BACKEND_CORS_ORIGINS=[]
      - BROADCAST_URI=redis://redis:6379
      - API_SQLA_URI=mysql+pymysql://test_root:aXMHcwPm4fMJa@81.181.255.414:3306/test_explorer?charset=utf8mb4
      - CHAIN_ID=polkadot
      - SENTRY_PROJECT_NAME=explorer-api-v2
      - SENTRY_SERVER_NAME=polkadapt
      - SENTRY_DSN=

##Note: enable when running with Signoz telemetry
#networks:
#    clickhouse-setup_default: # external signoz created network
#        external: true
```

**Comment by matthijsb** [comment]
This project is only tested on linux based systems, it seems there is a mismatch in EOF handling between windows / posix systems. You can run this on windows, but you should use WSL 2: https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by SWS-5007** [comment]
> This project is only tested on linux based systems, it seems there is a mismatch in EOF handling between windows / posix systems. You can run this on windows, but you should use WSL 2: https://learn.microsoft.com/en-us/windows/wsl/install

Hi,
I installed Ubuntu on VM and run this api with `docker-compose up --build` command, I am getting same error.

> unexpected EOF

What is wrong?

**Comment by SWS-5007** [comment]
One more question.
To run this API, I am running only this command, `docker-compose up --build` in root of explorer-api.

Then, I can see many sections in `README.MD` of `explorer-api` repo.
For example, `Add GraphQL query logging`, `Add telemetry using Signoz` etc.
So Which way is the best to run this api?
Can't I run this api by using only `docker-compose up --build` as I can see first of this `README.MD`

**Comment by matthijsb** [comment]
Running using "docker-compose up --build" should work, we've tested this on WSL 2, native Ubuntu and MacOS. Which Ubuntu version did you use? And did you do a fresh checkout when running docker-compose?

**Comment by SWS-5007** [comment]
> Running using "docker-compose up --build" should work, we've tested this on WSL 2, native Ubuntu and MacOS. Which Ubuntu version did you use? And did you do a fresh checkout when running docker-compose?

I am using the Ubuntu 22.04 on AWS.
`And did you do a fresh checkout when running docker-compose?`
How can I do this?

**Comment by matthijsb** [comment]
Just tested on WSL 2 (ubuntu 20.04): 

git clone https://github.com/polkascan/explorer-api.git

modified the docker-compose.yml:

`
version: "3"

services:
  #db:
  #  image: mysql
  #  hostname: mysql
  #  environment:
  #    MYSQL_ROOT_PASSWORD: root
  #    MYSQL_DATABASE: explorer_api
  #  ports:
  #    - "3307:3306"

  redis:
    image: "redis:latest"

  polling:
    build:
      context: .
      dockerfile: ./docker/polling/Dockerfile
    image: polkascan/explorer-polling-beta
    command: python polling.py
    depends_on:
      - redis
    #  - db
      - api
    environment:
      - DB_USERNAME=test_root
      - DB_NAME=test_explorer
      - DB_HOST=81.181.255.414
      - DB_PORT=3306
      - DB_PASSWORD=aXMHcwPm4fMJa
      - BROADCAST_URI=redis://redis:6379
      - CHAIN_ID=polkadot
      - SENTRY_PROJECT_NAME=explorer-polling-v2
      - SENTRY_SERVER_NAME=polkadapt
      - SENTRY_DSN=

  api:
    build:
      context: .
      dockerfile: ${API_DOCKER_FILE:-./docker/api/Dockerfile}
    image: ${API_DOCKER_IMAGE:-polkascan/explorer-api-beta}
    command: ${API_DOCKER_COMMAND:-bash -c "/usr/src/start-api.sh"}
    ports:
      - "8000:8000"
    depends_on:
      - redis
      #- db
#    # Note: enable when running with Signoz telemetry
#    networks:
#        - default
#        - clickhouse-setup_default
    environment:
      - DB_USERNAME=test_root
      - DB_NAME=test_explorer
      - DB_HOST=81.181.255.414
      - DB_PORT=3306
      - BLOCK_LIMIT_COUNT=500000
      - HTTP_MOUNT=/graphql/
      - WS_MOUNT=/graphql-ws/
      - DB_HARVESTER_NAME=polkascan
      - DB_PASSWORD=aXMHcwPm4fMJa
      - DOMAIN=localhost
      - SERVER_ADDR=localhost
      - SERVER_PORT=8000
      - WEBSOCKET_URI=ws://localhost:8000
      - BACKEND_CORS_ORIGINS=[]
      - BROADCAST_URI=redis://redis:6379
      #- API_SQLA_URI=mysql+pymysql://root:root@mysql:3306/explorer_api?charset=utf8mb4
      - API_SQLA_URI=mysql+pymysql://test_root:aXMHcwPm4fMJa@81.181.255.414:3306/test_explorer?charset=utf8mb
      - CHAIN_ID=polkadot
      - SENTRY_PROJECT_NAME=explorer-api-v2
      - SENTRY_SERVER_NAME=polkadapt
      - SENTRY_DSN=

##Note: enable when running with Signoz telemetry
#networks:
#    clickhouse-setup_default: # external signoz created network
#        external: true
`

Then run it:

docker-compose up --build

But can't test further since the IP is probably a private one:

polling_1  | ERROR:__main__:(2003, "Can't connect to MySQL server on '81.181.255.414'")
polling_1  | WARNING:__main__:Finished call to '__main__.get_connection' after 13.128(s), this was the 14th time calling it.
api_1      | ERROR:__main__:(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '81.181.255.414' ([Errno -2] Name or service not known)")
api_1      | (Background on this error at: http://sqlalche.me/e/13/e3q8)
api_1      | WARNING:__main__:Finished call to '__main__.init' after 14.265(s), this was the 15th time calling it.

**Comment by SWS-5007** [comment]
Okay, 
Then, please test with my real database info.

```
version: "3"

services:
  # db:
  #   image: mysql
  #   hostname: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: admin12345
  #     MYSQL_DATABASE: shearscan_explorer
  #   ports:
  #     - "3307:3306"

  redis:
    image: "redis:latest"

  polling:
    build:
      context: .
      dockerfile: ./docker/polling/Dockerfile
    image: polkascan/explorer-polling-beta
    command: python polling.py
    depends_on:
      - redis
      # - db
      - api
    environment:
      - DB_USERNAME=explorer_admin
      - DB_NAME=shearscan_explorer
      - DB_HOST=shearscan-db.czs1e81qdbcu.eu-central-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_PASSWORD=admin12345
      - BROADCAST_URI=redis://redis:6379
      - CHAIN_ID=polkadot
      - SENTRY_PROJECT_NAME=explorer-polling-v2
      - SENTRY_SERVER_NAME=polkadapt
      - SENTRY_DSN=

  api:
    build:
      context: .
      dockerfile: ${API_DOCKER_FILE:-./docker/api/Dockerfile}
    image: ${API_DOCKER_IMAGE:-polkascan/explorer-api-beta}
    command: ${API_DOCKER_COMMAND:-bash -c "/usr/src/start-api.sh"}
    ports:
      - "8000:8000"
    depends_on:
      - redis
      # - db
#    # Note: enable when running with Signoz telemetry
#    networks:
#        - default
#        - clickhouse-setup_default
    environment:
      - DB_USERNAME=explorer_admin
      - DB_NAME=shearscan_explorer
      - DB_HOST=shearscan-db.czs1e81qdbcu.eu-central-1.rds.amazonaws.com
      - DB_PORT=3306
      - BLOCK_LIMIT_COUNT=500000
      - HTTP_MOUNT=/graphql/
      - WS_MOUNT=/graphql-ws/
      - DB_HARVESTER_NAME=polkascan
      - DB_PASSWORD=admin12345
      - DOMAIN=localhost
      - SERVER_ADDR=localhost
      - SERVER_PORT=8000
      - WEBSOCKET_URI=ws://localhost:8000
      - BACKEND_CORS_ORIGINS=[]
      - BROADCAST_URI=redis://redis:6379
      - API_SQLA_URI=mysql+pymysql://explorer_admin:admin12345@shearscan-db.czs1e81qdbcu.eu-central-1.rds.amazonaws.com:3306/shearscan_explorer?charset=utf8mb4
      - CHAIN_ID=polkadot
      - SENTRY_PROJECT_NAME=explorer-api-v2
      - SENTRY_SERVER_NAME=polkadapt
      - SENTRY_DSN=

##Note: enable when running with Signoz telemetry
#networks:
#    clickhouse-setup_default: # external signoz created network
#        external: true
```

**Comment by SWS-5007** [comment]
With above config, I am getting some issues yet,
Here is entire log after I run the `docker-compose up --build` command below.

```
 ⠿ Container explorer-api-polling-1  Created                                                                                                                                            0.0s
Attaching to explorer-api-api-1, explorer-api-polling-1, explorer-api-redis-1
explorer-api-redis-1    | 1:C 06 Feb 2023 14:35:36.349 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
explorer-api-redis-1    | 1:C 06 Feb 2023 14:35:36.349 # Redis version=7.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
explorer-api-redis-1    | 1:C 06 Feb 2023 14:35:36.349 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
explorer-api-redis-1    | 1:M 06 Feb 2023 14:35:36.351 * monotonic clock: POSIX clock_gettime
explorer-api-redis-1    | 1:M 06 Feb 2023 14:35:36.355 * Running mode=standalone, port=6379.
explorer-api-redis-1    | 1:M 06 Feb 2023 14:35:36.355 # Server initialized
explorer-api-redis-1    | 1:M 06 Feb 2023 14:35:36.355 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
explorer-api-redis-1    | 1:M 06 Feb 2023 14:35:36.356 # WARNING Your system is configured to use the 'xen' clocksource which might lead to degraded performance. Check the result of the [slow-clocksource] system check: run 'redis-server --check-system' to check if the system's clocksource isn't degrading performance.
explorer-api-redis-1    | 1:M 06 Feb 2023 14:35:36.360 * Loading RDB produced by version 7.0.8
explorer-api-redis-1    | 1:M 06 Feb 2023 14:35:36.360 * RDB age 7864 seconds
explorer-api-redis-1    | 1:M 06 Feb 2023 14:35:36.360 * RDB memory usage when created 0.82 Mb
explorer-api-redis-1    | 1:M 06 Feb 2023 14:35:36.360 * Done loading RDB, keys loaded: 0, keys expired: 0.
explorer-api-redis-1    | 1:M 06 Feb 2023 14:35:36.360 * DB loaded from disk: 0.003 seconds
explorer-api-redis-1    | 1:M 06 Feb 2023 14:35:36.360 * Ready to accept connections
explorer-api-polling-1  | INFO:asyncio_redis:Connecting to redis
explorer-api-polling-1  | INFO:asyncio_redis:Redis connection made
explorer-api-polling-1  | INFO:asyncio_redis:Connecting to redis
explorer-api-polling-1  | INFO:asyncio_redis:Redis connection made
explorer-api-api-1      | 2023-02-06 14:35:39,874 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'sql_mode'
explorer-api-api-1      | INFO  [sqlalchemy.engine.base.Engine] SHOW VARIABLES LIKE 'sql_mode'
explorer-api-api-1      | 2023-02-06 14:35:39,875 INFO sqlalchemy.engine.base.Engine {}
explorer-api-api-1      | INFO  [sqlalchemy.engine.base.Engine] {}
explorer-api-api-1      | 2023-02-06 14:35:39,878 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'lower_case_table_names'
explorer-api-api-1      | INFO  [sqlalchemy.engine.base.Engine] SHOW VARIABLES LIKE 'lower_case_table_names'
explorer-api-api-1      | 2023-02-06 14:35:39,878 INFO sqlalchemy.engine.base.Engine {}
explorer-api-api-1      | INFO  [sqlalchemy.engine.base.Engine] {}
explorer-api-api-1      | 2023-02-06 14:35:39,882 INFO sqlalchemy.engine.base.Engine SELECT DATABASE()
explorer-api-api-1      | INFO  [sqlalchemy.engine.base.Engine] SELECT DATABASE()
explorer-api-api-1      | 2023-02-06 14:35:39,882 INFO sqlalchemy.engine.base.Engine {}
explorer-api-api-1      | INFO  [sqlalchemy.engine.base.Engine] {}
explorer-api-api-1      | 2023-02-06 14:35:39,884 INFO sqlalchemy.engine.base.Engine show collation where `Charset` = 'utf8mb4' and `Collation` = 'utf8mb4_bin'
explorer-api-api-1      | INFO  [sqlalchemy.engine.base.Engine] show collation where `Charset` = 'utf8mb4' and `Collation` = 'utf8mb4_bin'
explorer-api-api-1      | 2023-02-06 14:35:39,885 INFO sqlalchemy.engine.base.Engine {}
explorer-api-api-1      | INFO  [sqlalchemy.engine.base.Engine] {}
explorer-api-api-1      | 2023-02-06 14:35:39,887 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS CHAR(60)) AS anon_1
explorer-api-api-1      | INFO  [sqlalchemy.engine.base.Engine] SELECT CAST('test plain returns' AS CHAR(60)) AS anon_1
explorer-api-api-1      | 2023-02-06 14:35:39,888 INFO sqlalchemy.engine.base.Engine {}
explorer-api-api-1      | INFO  [sqlalchemy.engine.base.Engine] {}
explorer-api-api-1      | 2023-02-06 14:35:39,889 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS CHAR(60)) AS anon_1
explorer-api-api-1      | INFO  [sqlalchemy.engine.base.Engine] SELECT CAST('test unicode returns' AS CHAR(60)) AS anon_1
explorer-api-api-1      | 2023-02-06 14:35:39,889 INFO sqlalchemy.engine.base.Engine {}
explorer-api-api-1      | INFO  [sqlalchemy.engine.base.Engine] {}
explorer-api-api-1      | 2023-02-06 14:35:39,892 INFO sqlalchemy.engine.base.Engine SELECT CAST('test collated returns' AS CHAR CHARACTER SET utf8mb4) COLLATE utf8mb4_bin AS anon_1
explorer-api-api-1      | INFO  [sqlalchemy.engine.base.Engine] SELECT CAST('test collated returns' AS CHAR CHARACTER SET utf8mb4) COLLATE utf8mb4_bin AS anon_1
explorer-api-api-1      | 2023-02-06 14:35:39,893 INFO sqlalchemy.engine.base.Engine {}
explorer-api-api-1      | INFO  [sqlalchemy.engine.base.Engine] {}
explorer-api-api-1      | 2023-02-06 14:35:39,896 INFO sqlalchemy.engine.base.Engine DESCRIBE `alembic_version`
explorer-api-api-1      | INFO  [sqlalchemy.engine.base.Engine] DESCRIBE `alembic_version`
explorer-api-api-1      | 2023-02-06 14:35:39,896 INFO sqlalchemy.engine.base.Engine {}
explorer-api-api-1      | INFO  [sqlalchemy.engine.base.Engine] {}
explorer-api-api-1      | 2023-02-06 14:35:39,899 INFO sqlalchemy.engine.base.Engine SELECT alembic_version.version_num
explorer-api-api-1      | FROM alembic_version
explorer-api-api-1      | INFO  [sqlalchemy.engine.base.Engine] SELECT alembic_version.version_num
explorer-api-api-1      | FROM alembic_version
explorer-api-api-1      | 2023-02-06 14:35:39,899 INFO sqlalchemy.engine.base.Engine {}
explorer-api-api-1      | INFO  [sqlalchemy.engine.base.Engine] {}
explorer-api-api-1      | INFO:__main__:Tagged account import started...
explorer-api-api-1      | INFO:__main__:Tagged account import finished
explorer-api-api-1      | INFO:     Started server process [1]
explorer-api-api-1      | INFO:     Waiting for application startup.
explorer-api-api-1      | INFO:     Application startup complete.
explorer-api-api-1      | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

```

**Comment by SWS-5007** [comment]
What is wrong yet?
What should I do now?

**Comment by arjanz** [comment]
From the looks of it, nothing is wrong? Maybe the debug info is a bit confusing (executed SQL queries) but the service is running (`Uvicorn running on http://0.0.0.0:8000`). 

Be aware this only started the API and not the harvester, so no data will be processed. I assume you have the harvester running elsewhere?

If not, the docker-compose containing all necessary services can be found here: https://github.com/polkascan/explorer/blob/main/docker-compose.yml

Again, my recommendation would be in your case to just run mentioned docker-compose file with `docker-compose up -d --build`, and also use the MySQL DB included in this docker-compose file on a AWS EC2, then no further DevOps knowledge is required.

**Comment by SWS-5007** [comment]
Now, I am trying to run this explorer with harvester and api.
I am executing the `docker compose up --build` command in the root of explorer.
But I am issue error below.
![image](https://user-images.githubusercontent.com/119567356/217243036-00b848d8-5f82-482f-9cb9-3ee8a773ee0c.png)
As you can see here, this command doesn't work well.
What is wrong?

**Comment by matthijsb** [comment]
Im closing this here since it is not explorer-api related, for more info see here:

https://github.com/polkascan/explorer/issues/24
