### ISSUE TITLE
How to run with own server database config?

### ISSUE THREAD

**Issue by SWS-5007** [polkascan/explorer-api#22]
Hi, 
I am going to run this api with my server database.
For this, how should I change the docker-compose.yml file config?
Here is my server database info.
```
Host: test-db.czs1e81qdbcu.eu-central-1.rds.amazonaws.com
DB Name: test_db
DB UserName: root
DB Password: root12345
```

I have changed docker-compose.yml file with this database info like below.
```
version: "3"

services:
  db:
    image: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root12345
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"

  redis:
    image: "redis:latest"

  polling:
    build:
      context: .
      dockerfile: ./docker/polling/Dockerfile
    image: polkascan/explorer-polling-beta
    command: python polling.py
    depends_on:
      - redis
      - db
      - api
    environment:
      - DB_USERNAME=root
      - DB_NAME=test_db
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_PASSWORD=root12345
      - BROADCAST_URI=redis://redis:6379
      - CHAIN_ID=polkadot
      - SENTRY_PROJECT_NAME=explorer-polling-v2
      - SENTRY_SERVER_NAME=polkadapt
      - SENTRY_DSN=

  api:
    build:
      context: .
      dockerfile: ${API_DOCKER_FILE:-./docker/api/Dockerfile}
    image: ${API_DOCKER_IMAGE:-polkascan/explorer-api-beta}
    command: ${API_DOCKER_COMMAND:-bash -c "/usr/src/start-api.sh"}
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
#    # Note: enable when running with Signoz telemetry
#    networks:
#        - default
#        - clickhouse-setup_default
    environment:
      - DB_USERNAME=root
      - DB_NAME=test_db
      - DB_HOST=mysql
      - DB_PORT=3306
      - BLOCK_LIMIT_COUNT=500000
      - HTTP_MOUNT=/graphql/
      - WS_MOUNT=/graphql-ws/
      - DB_HARVESTER_NAME=polkascan
      - DB_PASSWORD=root12345
      - DOMAIN=localhost
      - SERVER_ADDR=localhost
      - SERVER_PORT=8000
      - WEBSOCKET_URI=ws://localhost:8000
      - BACKEND_CORS_ORIGINS=[]
      - BROADCAST_URI=redis://redis:6379
      - API_SQLA_URI=mysql+pymysql://root:root12345@test-db.czs1e81qdbcu.eu-central-1.rds.amazonaws.com:3306/test_db?charset=utf8mb4
      - CHAIN_ID=polkadot
      - SENTRY_PROJECT_NAME=explorer-api-v2
      - SENTRY_SERVER_NAME=polkadapt
      - SENTRY_DSN=

##Note: enable when running with Signoz telemetry
#networks:
#    clickhouse-setup_default: # external signoz created network
#        external: true
```
Then, When I run this command, docker-compose up --build, I am getting error below.

> ...
> explorer-api-polling-1  | ERROR:__main__:(2003, "Can't connect to MySQL server on 'mysql'")
> explorer-api-polling-1  | WARNING:__main__:Finished call to '__main__.get_connection' after 11.052(s), this was the 12th time calling it.
> explorer-api-polling-1  | ERROR:__main__:(2003, "Can't connect to MySQL server on 'mysql'")
> explorer-api-polling-1  | WARNING:__main__:Finished call to '__main__.get_connection' after 12.056(s), this was the 13th time calling it.
> 

What is wrong?
And How should I solve this issue?

**Comment by matthijsb** [comment]
you should comment out the DB section then, since you're providing the DB yourself:

`  #db:
   # image: mysql
   # hostname: mysql
    #environment:
     # MYSQL_ROOT_PASSWORD: #######
     # MYSQL_DATABASE: test_db
    #ports:
     # - "3307:3306"`
     
And then point to your own server instead of the docker-compose one in the environment vars:

DB_HOST=test-db.czs1e81qdbcu.eu-central-1.rds.amazonaws.com

PS: i understand it is a test db / passport, but you should probably change it and never share such info online ;-)

**Comment by SWS-5007** [comment]
> you should comment out the DB section then, since you're providing the DB yourself:
> 
> ` #db:
> 
> # image: mysql
> # hostname: mysql
> ```
> #environment:
>  # MYSQL_ROOT_PASSWORD: #######
>  # MYSQL_DATABASE: test_db
> #ports:
>  # - "3307:3306"`
> ```
> 
> And then point to your own server instead of the docker-compose one in the environment vars:
> 
> DB_HOST=test-db.czs1e81qdbcu.eu-central-1.rds.amazonaws.com
> 
> PS: i understand it is a test db / passport, but you should probably change it and never share such info online ;-)

`And then point to your own server instead of the docker-compose one in the environment vars:
`
Could you tell me about this more kindly based on my database info?

**Comment by SWS-5007** [comment]
I have changed `docker-compose.yml` file like below as you said.
Please check carefully and let me know what I should change more.

```
version: "3"

services:
  # db:
  #   image: mysql
  #   hostname: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root12345
  #     MYSQL_DATABASE: test_db
  #   ports:
  #     - "3307:3306"

  redis:
    image: "redis:latest"

  polling:
    build:
      context: .
      dockerfile: ./docker/polling/Dockerfile
    image: polkascan/explorer-polling-beta
    command: python polling.py
    depends_on:
      - redis
      # - db
      - api
    environment:
      - DB_USERNAME=root
      - DB_NAME=test_db
      - DB_HOST=test-db.czs1e81qdbcu.eu-central-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_PASSWORD=root12345
      - BROADCAST_URI=redis://redis:6379
      - CHAIN_ID=polkadot
      - SENTRY_PROJECT_NAME=explorer-polling-v2
      - SENTRY_SERVER_NAME=polkadapt
      - SENTRY_DSN=

  api:
    build:
      context: .
      dockerfile: ${API_DOCKER_FILE:-./docker/api/Dockerfile}
    image: ${API_DOCKER_IMAGE:-polkascan/explorer-api-beta}
    command: ${API_DOCKER_COMMAND:-bash -c "/usr/src/start-api.sh"}
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
#    # Note: enable when running with Signoz telemetry
#    networks:
#        - default
#        - clickhouse-setup_default
    environment:
      - DB_USERNAME=root
      - DB_NAME=test_db
      - DB_HOST=test-db.czs1e81qdbcu.eu-central-1.rds.amazonaws.com
      - DB_PORT=3306
      - BLOCK_LIMIT_COUNT=500000
      - HTTP_MOUNT=/graphql/
      - WS_MOUNT=/graphql-ws/
      - DB_HARVESTER_NAME=polkascan
      - DB_PASSWORD=root12345
      - DOMAIN=localhost
      - SERVER_ADDR=localhost
      - SERVER_PORT=8000
      - WEBSOCKET_URI=ws://localhost:8000
      - BACKEND_CORS_ORIGINS=[]
      - BROADCAST_URI=redis://redis:6379
      - API_SQLA_URI=mysql+pymysql://root:root12345@test-db.czs1e81qdbcu.eu-central-1.rds.amazonaws.com:3306/test_db?charset=utf8mb4
      - CHAIN_ID=polkadot
      - SENTRY_PROJECT_NAME=explorer-api-v2
      - SENTRY_SERVER_NAME=polkadapt
      - SENTRY_DSN=

##Note: enable when running with Signoz telemetry
#networks:
#    clickhouse-setup_default: # external signoz created network
#        external: true
```

Best regards.

**Comment by matthijsb** [comment]
> > you should comment out the DB section then, since you're providing the DB yourself:
 `And then point to your own server instead of the docker-compose one in the environment vars: ` Could you tell me about this more kindly based on my database info?

Well, we use the default mysql docker image, you can interact with a running container to find all this yourself; it is not in my capacity to help everyone with their own specific configurations of these docker files. As of now, the mysql version is  MySQL Server 8.0.32-1.el8 (which i just requested from the docker container after starting it up)

The problem you are facing is that the mysql container you replaced with your own endpoint uses a different mysql server version, which is not compatible.

I recommend you get acquainted with docker and docker-compose first.

https://www.docker.com/101-tutorial/
https://medium.com/dev-sec-ops/docker-101-docker-compose-db96ae884cda

Hope that helps!
