### ISSUE TITLE
how to init tables

### ISSUE THREAD

**Issue by blackjooohn** [polkascan/explorer-api#3]
pymysql.err.ProgrammingError: (1146, "Table 'explorer_api.explorer_block' doesn't exist")

**Comment by matthijsb** [comment]
The models have been seperated from the harvester process, im afraid this has to wait for harvester v2 to be released (which also scrapes the required data into these models)..

**Comment by matthijsb** [comment]
models & harvester functionality have been added in fae82a859adae5b09943d247c816ef9d852c4838
